"""added ver tables2

Revision ID: 334b04a606ad
Revises: 8064f0b691e1
Create Date: 2025-03-07 16:02:40.458541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334b04a606ad'
down_revision: Union[str, None] = '8064f0b691e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('access_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_records')
    # ### end Alembic commands ###
