"""add parish station rbac settings models

Revision ID: 8a673816121b
Revises: 526be09a30a9
Create Date: 2026-03-13 17:09:08.976313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a673816121b'
down_revision: Union[str, None] = '526be09a30a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('diocese', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('pastor_name', sa.String(length=200), nullable=True),
    sa.Column('pastor_email', sa.String(length=200), nullable=True),
    sa.Column('pastor_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parish_id'), 'parish', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('parish_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parish.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_parish_settings_id'), 'parish_settings', ['id'], unique=False)
    op.create_index(op.f('ix_parish_settings_parish_id'), 'parish_settings', ['parish_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parish_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('MAIN_CHURCH', 'OUTSTATION', name='stationtype'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('location_description', sa.String(length=500), nullable=True),
    sa.Column('google_maps_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('priest_in_charge', sa.String(length=200), nullable=True),
    sa.Column('priest_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parish_id'], ['parish.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_index(op.f('ix_stations_parish_id'), 'stations', ['parish_id'], unique=False)
    op.create_table('mass_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', name='dayofweek'), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('mass_type', sa.Enum('SUNDAY', 'WEEKDAY', 'SATURDAY', 'HOLY_DAY', 'SPECIAL', name='masstype'), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mass_schedules_id'), 'mass_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_mass_schedules_station_id'), 'mass_schedules', ['station_id'], unique=False)
    op.add_column('church_communities', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_church_communities_station_id'), 'church_communities', ['station_id'], unique=False)
    op.create_foreign_key(None, 'church_communities', 'stations', ['station_id'], ['id'], ondelete='SET NULL')
    op.alter_column('par_family', 'spouse_status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('ALIVE', 'DECEASED', 'UNKNOWN', name='lifestatus'),
               existing_nullable=True,
               postgresql_using="spouse_status::lifestatus")
    op.add_column('parishioners', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_parishioners_church_community_id'), 'parishioners', ['church_community_id'], unique=False)
    op.create_index(op.f('ix_parishioners_email_address'), 'parishioners', ['email_address'], unique=False)
    op.create_index(op.f('ix_parishioners_membership_status'), 'parishioners', ['membership_status'], unique=False)
    op.create_index(op.f('ix_parishioners_mobile_number'), 'parishioners', ['mobile_number'], unique=False)
    op.create_index(op.f('ix_parishioners_new_church_id'), 'parishioners', ['new_church_id'], unique=False)
    op.create_index(op.f('ix_parishioners_old_church_id'), 'parishioners', ['old_church_id'], unique=False)
    op.create_index(op.f('ix_parishioners_station_id'), 'parishioners', ['station_id'], unique=False)
    op.create_index(op.f('ix_parishioners_verification_status'), 'parishioners', ['verification_status'], unique=False)
    op.drop_constraint('parishioners_place_of_worship_id_fkey', 'parishioners', type_='foreignkey')
    op.create_foreign_key(None, 'parishioners', 'stations', ['station_id'], ['id'], ondelete='SET NULL')
    op.drop_column('parishioners', 'place_of_worship_id')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'USER', name='userrole'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_column('users', 'role_id')
    op.add_column('parishioners', sa.Column('place_of_worship_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'parishioners', type_='foreignkey')
    op.create_foreign_key('parishioners_place_of_worship_id_fkey', 'parishioners', 'places_of_worship', ['place_of_worship_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_parishioners_verification_status'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_station_id'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_old_church_id'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_new_church_id'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_mobile_number'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_membership_status'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_email_address'), table_name='parishioners')
    op.drop_index(op.f('ix_parishioners_church_community_id'), table_name='parishioners')
    op.drop_column('parishioners', 'station_id')
    op.alter_column('par_family', 'spouse_status',
               existing_type=sa.Enum('ALIVE', 'DECEASED', 'UNKNOWN', name='lifestatus'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'church_communities', type_='foreignkey')
    op.drop_index(op.f('ix_church_communities_station_id'), table_name='church_communities')
    op.drop_column('church_communities', 'station_id')
    op.drop_index(op.f('ix_mass_schedules_station_id'), table_name='mass_schedules')
    op.drop_index(op.f('ix_mass_schedules_id'), table_name='mass_schedules')
    op.drop_table('mass_schedules')
    op.drop_index(op.f('ix_stations_parish_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_parish_settings_parish_id'), table_name='parish_settings')
    op.drop_index(op.f('ix_parish_settings_id'), table_name='parish_settings')
    op.drop_table('parish_settings')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_parish_id'), table_name='parish')
    op.drop_table('parish')
    # ### end Alembic commands ###
