"""Initial migration

Revision ID: 908b9c48d548
Revises: 
Create Date: 2025-04-04 16:10:48.889540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908b9c48d548'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('church_communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_church_communities_id'), 'church_communities', ['id'], unique=False)
    op.create_table('par_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_par_languages_id'), 'par_languages', ['id'], unique=False)
    op.create_table('par_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_par_skills_id'), 'par_skills', ['id'], unique=False)
    op.create_table('parishioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_church_id', sa.String(), nullable=True),
    sa.Column('new_church_id', sa.String(), nullable=True),
    sa.Column('membership_status', sa.Enum('ACTIVE', 'DECEASED', 'DISABLED', name='membershipstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'PENDING', name='verificationstatus'), server_default='UNVERIFIED', nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('other_names', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('maiden_name', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'WIDOWED', 'DIVORCED', name='maritalstatus'), server_default='SINGLE', nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('place_of_worship', sa.String(), nullable=True),
    sa.Column('current_residence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parishioners_id'), 'parishioners', ['id'], unique=False)
    op.create_table('places_of_worship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('mass_schedule', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_places_of_worship_id'), 'places_of_worship', ['id'], unique=False)
    op.create_table('sacrament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('once_only', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sacrament_id'), 'sacrament', ['id'], unique=False)
    op.create_table('societies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_inaugurated', sa.Date(), nullable=True),
    sa.Column('meeting_frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'CUSTOM', name='meetingfrequency'), nullable=False),
    sa.Column('meeting_day', sa.String(), nullable=True),
    sa.Column('meeting_time', sa.Time(), nullable=True),
    sa.Column('meeting_venue', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_societies_id'), 'societies', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'RESET_REQUIRED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('par_emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('primary_phone', sa.String(), nullable=False),
    sa.Column('alternative_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_emergency_contacts_id'), 'par_emergency_contacts', ['id'], unique=False)
    op.create_table('par_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('spouse_name', sa.String(), nullable=True),
    sa.Column('spouse_status', sa.String(), nullable=True),
    sa.Column('spouse_phone', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('father_status', sa.Enum('ALIVE', 'DECEASED', 'UNKNOWN', name='parentalstatus'), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('mother_status', sa.Enum('ALIVE', 'DECEASED', 'UNKNOWN', name='parentalstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parishioner_id')
    )
    op.create_index(op.f('ix_par_family_id'), 'par_family', ['id'], unique=False)
    op.create_table('par_medical_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_medical_conditions_id'), 'par_medical_conditions', ['id'], unique=False)
    op.create_table('par_occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('employer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parishioner_id')
    )
    op.create_index(op.f('ix_par_occupations_id'), 'par_occupations', ['id'], unique=False)
    op.create_table('par_parishioner_languages',
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['par_languages.id'], ),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], )
    )
    op.create_table('par_parishioner_skills',
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['par_skills.id'], )
    )
    op.create_table('par_sacraments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('BAPTISM', 'FIRST_COMMUNION', 'CONFIRMATION', 'PENANCE', 'ANOINTING', 'HOLY_ORDERS', 'MATRIMONY', name='parsacramenttype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('minister', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_sacraments_id'), 'par_sacraments', ['id'], unique=False)
    op.create_table('par_society_members',
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], )
    )
    op.create_table('society_leadership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('society_id', sa.Integer(), nullable=True),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('PRESIDENT', 'VICE_PRESIDENT', 'SECRETARY', 'TREASURER', 'CHAPLAIN', 'COORDINATOR', 'PATRON', 'OTHER', name='leadershiprole'), nullable=False),
    sa.Column('custom_role', sa.String(), nullable=True),
    sa.Column('elected_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_society_leadership_id'), 'society_leadership', ['id'], unique=False)
    op.create_table('verification_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('access_code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('par_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_info_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_info_id'], ['par_family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_children_id'), 'par_children', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_par_children_id'), table_name='par_children')
    op.drop_table('par_children')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_society_leadership_id'), table_name='society_leadership')
    op.drop_table('society_leadership')
    op.drop_table('par_society_members')
    op.drop_index(op.f('ix_par_sacraments_id'), table_name='par_sacraments')
    op.drop_table('par_sacraments')
    op.drop_table('par_parishioner_skills')
    op.drop_table('par_parishioner_languages')
    op.drop_index(op.f('ix_par_occupations_id'), table_name='par_occupations')
    op.drop_table('par_occupations')
    op.drop_index(op.f('ix_par_medical_conditions_id'), table_name='par_medical_conditions')
    op.drop_table('par_medical_conditions')
    op.drop_index(op.f('ix_par_family_id'), table_name='par_family')
    op.drop_table('par_family')
    op.drop_index(op.f('ix_par_emergency_contacts_id'), table_name='par_emergency_contacts')
    op.drop_table('par_emergency_contacts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_societies_id'), table_name='societies')
    op.drop_table('societies')
    op.drop_index(op.f('ix_sacrament_id'), table_name='sacrament')
    op.drop_table('sacrament')
    op.drop_index(op.f('ix_places_of_worship_id'), table_name='places_of_worship')
    op.drop_table('places_of_worship')
    op.drop_index(op.f('ix_parishioners_id'), table_name='parishioners')
    op.drop_table('parishioners')
    op.drop_index(op.f('ix_par_skills_id'), table_name='par_skills')
    op.drop_table('par_skills')
    op.drop_index(op.f('ix_par_languages_id'), table_name='par_languages')
    op.drop_table('par_languages')
    op.drop_index(op.f('ix_church_communities_id'), table_name='church_communities')
    op.drop_table('church_communities')
    # ### end Alembic commands ###
