"""add station_id to societies and users

Revision ID: 92b9019ef6af
Revises: 8a673816121b
Create Date: 2026-03-13 17:27:42.300429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b9019ef6af'
down_revision: Union[str, None] = '8a673816121b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('societies', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_societies_station_id'), 'societies', ['station_id'], unique=False)
    op.create_foreign_key(None, 'societies', 'stations', ['station_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('station_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_station_id'), 'users', ['station_id'], unique=False)
    op.create_foreign_key(None, 'users', 'stations', ['station_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_station_id'), table_name='users')
    op.drop_column('users', 'station_id')
    op.drop_constraint(None, 'societies', type_='foreignkey')
    op.drop_index(op.f('ix_societies_station_id'), table_name='societies')
    op.drop_column('societies', 'station_id')
    # ### end Alembic commands ###
