"""added new_church_id column

Revision ID: b2f412b5e686
Revises: e4f2ddcb1155
Create Date: 2025-02-23 13:50:51.733829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2f412b5e686'
down_revision: Union[str, None] = 'e4f2ddcb1155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parishioners', sa.Column('new_church_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parishioners', 'new_church_id')
    # ### end Alembic commands ###
