"""add parish_id to mass_schedules make outstation_id nullable

Revision ID: c28688039760
Revises: d21e83d1c2f8
Create Date: 2026-03-13 19:50:57.873391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28688039760'
down_revision: Union[str, None] = 'd21e83d1c2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mass_schedules', sa.Column('parish_id', sa.Integer(), nullable=True))
    op.alter_column('mass_schedules', 'outstation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_mass_schedules_parish_id'), 'mass_schedules', ['parish_id'], unique=False)
    op.create_foreign_key(None, 'mass_schedules', 'parish', ['parish_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mass_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_mass_schedules_parish_id'), table_name='mass_schedules')
    op.alter_column('mass_schedules', 'outstation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('mass_schedules', 'parish_id')
    # ### end Alembic commands ###
