"""remove outstation type column and enum

Revision ID: d21e83d1c2f8
Revises: 04e9cbc3c0ed
Create Date: 2026-03-13 17:47:36.894893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd21e83d1c2f8'
down_revision: Union[str, None] = '04e9cbc3c0ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column('outstations', 'type')
    op.execute("DROP TYPE IF EXISTS outstationtype")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outstations', sa.Column('type', postgresql.ENUM('MAIN_CHURCH', 'OUTSTATION', name='outstationtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
