"""initial migraton

Revision ID: df1c384f55ab
Revises: 
Create Date: 2025-02-24 13:36:57.078869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df1c384f55ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('par_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_par_skills_id'), 'par_skills', ['id'], unique=False)
    op.create_table('parishioners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_church_id', sa.String(), nullable=True),
    sa.Column('new_church_id', sa.String(), nullable=True),
    sa.Column('membership_status', sa.Enum('ACTIVE', 'DECEASED', 'DISABLED', name='membershipstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'VERIFIED', 'PENDING', name='verificationstatus'), server_default='UNVERIFIED', nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('other_names', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('maiden_name', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sa.String(), nullable=True),
    sa.Column('hometown', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'WIDOWED', 'DIVORCED', name='maritalstatus'), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parishioners_id'), 'parishioners', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'RESET_REQUIRED', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('par_emergency_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationshipp', sa.String(), nullable=False),
    sa.Column('primary_phone', sa.String(), nullable=False),
    sa.Column('alternative_phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_emergency_contacts_id'), 'par_emergency_contacts', ['id'], unique=False)
    op.create_table('par_family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('spouse_name', sa.String(), nullable=True),
    sa.Column('spouse_status', sa.String(), nullable=True),
    sa.Column('spouse_phone', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('father_status', sa.Enum('ALIVE', 'DECEASED', 'UNKNOWN', name='parentalstatus'), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('mother_status', sa.Enum('ALIVE', 'DECEASED', 'UNKNOWN', name='parentalstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parishioner_id')
    )
    op.create_index(op.f('ix_par_family_id'), 'par_family', ['id'], unique=False)
    op.create_table('par_medical_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_medical_conditions_id'), 'par_medical_conditions', ['id'], unique=False)
    op.create_table('par_occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('employer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parishioner_id')
    )
    op.create_index(op.f('ix_par_occupations_id'), 'par_occupations', ['id'], unique=False)
    op.create_table('par_parishioner_skills',
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['par_skills.id'], )
    )
    op.create_table('par_sacraments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parishioner_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('BAPTISM', 'FIRST_COMMUNION', 'CONFIRMATION', 'PENANCE', 'ANOINTING', 'HOLY_ORDERS', 'MATRIMONY', name='sacramenttype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('minister', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parishioner_id'], ['parishioners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_sacraments_id'), 'par_sacraments', ['id'], unique=False)
    op.create_table('par_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_info_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_info_id'], ['par_family.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_children_id'), 'par_children', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_par_children_id'), table_name='par_children')
    op.drop_table('par_children')
    op.drop_index(op.f('ix_par_sacraments_id'), table_name='par_sacraments')
    op.drop_table('par_sacraments')
    op.drop_table('par_parishioner_skills')
    op.drop_index(op.f('ix_par_occupations_id'), table_name='par_occupations')
    op.drop_table('par_occupations')
    op.drop_index(op.f('ix_par_medical_conditions_id'), table_name='par_medical_conditions')
    op.drop_table('par_medical_conditions')
    op.drop_index(op.f('ix_par_family_id'), table_name='par_family')
    op.drop_table('par_family')
    op.drop_index(op.f('ix_par_emergency_contacts_id'), table_name='par_emergency_contacts')
    op.drop_table('par_emergency_contacts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parishioners_id'), table_name='parishioners')
    op.drop_table('parishioners')
    op.drop_index(op.f('ix_par_skills_id'), table_name='par_skills')
    op.drop_table('par_skills')
    # ### end Alembic commands ###
