"""updated rel names

Revision ID: ef16fcb7b479
Revises: 9dfa12322381
Create Date: 2025-02-24 14:59:49.126874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef16fcb7b479'
down_revision: Union[str, None] = '9dfa12322381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('par_emergency_contacts', sa.Column('relationship', sa.String(), nullable=False))
    op.drop_column('par_emergency_contacts', 'relationshipp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('par_emergency_contacts', sa.Column('relationshipp', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('par_emergency_contacts', 'relationship')
    # ### end Alembic commands ###
