"""added status and data joined to society tablee

Revision ID: f85d1bcacbb0
Revises: 
Create Date: 2025-03-29 19:18:15.592825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f85d1bcacbb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('par_society_members', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('par_society_members', sa.Column('join_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('par_society_members', 'join_date')
    op.drop_column('par_society_members', 'status')
    # ### end Alembic commands ###
